const EASY_LEETCODE_UNLOCK_TIME = 6 * 60 * 60 * 1000;
const MEDIUM_LEETCODE_UNLOCK_TIME = 24 * 60 * 60 * 1000;
const HARD_LEETCODE_UNLOCK_TIME = 72 * 60 * 60 * 1000;

const ALARM_NAME = 'checkLeetCodeStatus';
const CHECK_INTERVAL_MINUTES = 1;

export {
    EASY_LEETCODE_UNLOCK_TIME,
    MEDIUM_LEETCODE_UNLOCK_TIME,
    HARD_LEETCODE_UNLOCK_TIME,
    ALARM_NAME,
    CHECK_INTERVAL_MINUTES
}